# Generated by Django 4.2.6 on 2023-10-16 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluongcauhoi', models.IntegerField()),
                ('tongdiem', models.FloatField()),
                ('hocvien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CauHoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaicauhoi', models.CharField(max_length=200)),
                ('noidung', models.TextField()),
                ('dapan1', models.TextField()),
                ('dapan2', models.TextField()),
                ('dapan3', models.TextField()),
                ('dapan4', models.TextField()),
                ('dapandung', models.IntegerField()),
                ('diem', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='KyThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenkythi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietBaiThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dapanchon', models.IntegerField()),
                ('diem', models.FloatField()),
                ('baithi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.baithi')),
                ('cauhoi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cauhoi')),
            ],
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='kythi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.kythi'),
        ),
        migrations.AddField(
            model_name='baithi',
            name='kythi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.kythi'),
        ),
    ]
