# Generated by Django 4.2.6 on 2023-10-17 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_baithi_cauhoi_kythi_chitietbaithi_cauhoi_kythi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baithi',
            old_name='kythi',
            new_name='kthi',
        ),
        migrations.RenameField(
            model_name='cauhoi',
            old_name='kythi',
            new_name='kthi',
        ),
        migrations.RenameField(
            model_name='chitietbaithi',
            old_name='baithi',
            new_name='bthi',
        ),
        migrations.RenameField(
            model_name='chitietbaithi',
            old_name='cauhoi',
            new_name='choi',
        ),
    ]
