# Generated by Django 4.2.6 on 2023-10-17 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_kythi_baithi_kthi_rename_kythi_cauhoi_kthi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baithi',
            old_name='kthi',
            new_name='kythi',
        ),
        migrations.RenameField(
            model_name='cauhoi',
            old_name='kthi',
            new_name='kythi',
        ),
        migrations.RenameField(
            model_name='chitietbaithi',
            old_name='bthi',
            new_name='baithi',
        ),
        migrations.RenameField(
            model_name='chitietbaithi',
            old_name='choi',
            new_name='cauhoi',
        ),
    ]
