# Generated by Django 4.2.6 on 2023-10-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_answer_question_quiz_quizresult_remove_cauhoi_kythi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('numberofquestion', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
