# Generated by Django 4.2.6 on 2023-10-19 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_quiz_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.quiz'),
        ),
    ]
