# Generated by Django 4.2.6 on 2023-10-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_quiz_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='scoreofquestion',
            field=models.FloatField(default=0),
        ),
    ]
