# Generated by Django 4.2.6 on 2023-10-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_course_scoreofquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='timeofquiz',
            field=models.IntegerField(default=0),
        ),
    ]
