# Generated by Django 4.2.6 on 2023-10-29 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_student_course_user_alter_quiz_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofquestion', models.IntegerField(default=0)),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Course_User',
        ),
    ]
