# Generated by Django 4.2.6 on 2023-10-29 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_course_student_delete_course_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_student',
            name='numberofquestion',
        ),
    ]
