# Generated by Django 4.2.6 on 2023-11-22 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_course_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='exam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.exam'),
        ),
        migrations.AlterField(
            model_name='course',
            name='timeofquiz',
            field=models.IntegerField(),
        ),
    ]
