# Generated by Django 4.2.6 on 2023-12-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_category_exam_alter_course_timeofquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
