# Generated by Django 4.2.6 on 2023-12-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='excellent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='good',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='outstanding',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='satisfactory',
            field=models.IntegerField(default=0),
        ),
    ]
