# Generated by Django 4.2.6 on 2023-12-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_exam_excellent_exam_fail_exam_good_exam_outstanding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='fail',
        ),
        migrations.AlterField(
            model_name='exam',
            name='excellent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='good',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='outstanding',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='satisfactory',
            field=models.IntegerField(),
        ),
    ]
